default: &default
  adapter: postgresql
  encoding: unicode
  database: pdxo4j
  pool: 2
  username: slackz
  password: <%= ENV['DATABASE_PW'] %>

development:
  <<: *default

production:
  <<: *default
