source 'https://rubygems.org'

gem 'activerecord', '~> 5.1.4'
gem 'bcrypt', '~> 3.1.11'
gem 'haml', '~> 5.0.4'
gem 'pg', '~> 0.21.0'
gem 'rake',  '~> 12.2.1'

gem 'sinatra-activerecord', '~> 2.0.13'
gem 'sinatra', '~> 2.0.0'

group :development do
  gem 'rerun', '~> 0.11.0'
  gem 'racksh', '~> 1.0.0'
end
